# Generated by Django 3.2.18 on 2023-08-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.SlugField(default='window', unique=True),
        ),
    ]
